---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: javawebappdeployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: javawebapp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: javawebapp
    spec:
      containers:
      - image: sachinpatel1979/java-web-app-docker
        name: javawebapp
        ports:
        - containerPort: 8080
---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  name: javawebappservice
spec:
  type: NodePort
  selector:
    app: javawebapp
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31673
